development: &default
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test: &test
  <<: *default
  database: db/test.sqlite3

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: foursquare4biz_production
  pool: 5
  username: root
  password: 
  socket: /tmp/mysql.sock
